import {exerciseDiagram} from './exercises.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function workoutMarkup(d,{state,today,previous}){
 const strength=d.sport==='strength',basket=d.sport==='basketball',live=strength&&d.started_at&&!d.ended_at;
 const date=`<label>运动日期<input type="date" name="date" value="${esc(d.date)}" max="${today}" required></label>`;
 const duration=`<label>用时（分钟）<input name="duration" inputmode="decimal" type="number" min="0.00001" max="10080" step="any" value="${esc(d.duration)}" placeholder="例如 30" ${live?'':'required'}></label>`;
 const notes=`<label>感受（选填）<textarea name="notes" rows="2" maxlength="2000" placeholder="今天状态怎么样？">${esc(d.notes)}</textarea></label>`;
 const details=`<details class="record-options" ${d.id?'open':''}><summary>${d.date===today?'今天':esc(d.date)} · 日期与备注</summary>${date}${notes}</details>`;
 let body='';
 if(basket)body=`<label>开始时间<input type="datetime-local" name="start" value="${esc(d.start)}" required></label><label>结束时间<input type="datetime-local" name="end" value="${esc(d.end)}" required></label><p class="hint">跨过午夜时，结束日期选第二天。</p>`;
 else if(!strength)body=`<div class="form-grid quick-fields"><label>距离（公里）<input name="distance" type="number" inputmode="decimal" min="0.001" max="10000" step="0.001" value="${esc(d.distance)}" placeholder="例如 5" required></label>${duration}</div>${details}`;
 else{
  body=`<div class="training-heading"><div><span class="hint">${live?'正在训练 · 今天':d.id?'编辑训练':'补记训练'}</span>${live?'<strong class="timer" id="workout-timer">00:00</strong>':''}</div>${!d.id?`<button type="button" class="small ghost" data-action="entry-mode">${live?'改为补记':'现在开始训练'}</button>`:''}</div>${live?'':`<div class="form-grid">${date}${duration}</div>`}`;
  if(!d.exercises.length)body+=`<div class="training-empty"><h3>今天练什么？</h3><p class="hint">选好动作，就能直接记每一组。</p></div>${state.templates.length?`<div class="template-shortcuts">${state.templates.map(t=>`<button type="button" data-action="use-template" data-id="${esc(t.id)}">${esc(t.name)}</button>`).join('')}</div>`:''}`;
  body+=`<div id="exercise-list">${d.exercises.map((e,i)=>{
   const info=state.exercises.find(x=>x.id===e.exercise_id),prev=previous(e.exercise_id),last=prev?.exercises.find(x=>x.exercise_id===e.exercise_id)?.sets.filter(s=>s.completed)||[];
   return `<section class="exercise-card"><div class="row between"><div><h3>${esc(e.name)}</h3><p class="hint">${esc(e.weight_basis)} · kg</p></div><details class="exercise-menu"><summary aria-label="${esc(e.name)}更多操作">•••</summary><button type="button" class="small ghost danger" data-action="remove-exercise" data-index="${i}">移除动作</button></details></div>${last.length?`<div class="last-training"><span>上次 ${last.map(s=>`${s.weight_kg} × ${s.reps}`).join(' / ')}</span><button type="button" class="small ghost" data-action="copy-previous" data-index="${i}">沿用</button></div>`:''}<div class="set-row set-head"><span>组</span><span>公斤</span><span>次数</span><span>完成</span><span></span></div>${e.sets.map((s,j)=>`<div class="set-row ${s.completed?'is-done':''}"><span class="index">${j+1}</span><input name="weight-${i}-${j}" type="number" inputmode="decimal" value="${esc(s.weight)}" min="0" max="5000" step="0.01" ${s.completed?'required':''} aria-label="${esc(e.name)}第${j+1}组重量"><input name="reps-${i}-${j}" type="number" inputmode="numeric" value="${esc(s.reps)}" min="1" max="10000" step="1" ${s.completed?'required':''} aria-label="${esc(e.name)}第${j+1}组次数"><input type="checkbox" name="done-${i}-${j}" ${s.completed?'checked':''} aria-label="${esc(e.name)}第${j+1}组已完成"><button type="button" class="ghost" data-action="remove-set" data-index="${i}" data-set="${j}" aria-label="删除${esc(e.name)}第${j+1}组"><span class="ui-icon ui-icon-close" aria-hidden="true"></span></button></div>`).join('')}<button type="button" class="small ghost full spaced" data-action="add-set" data-index="${i}">＋ 添加一组</button><details class="exercise-help"><summary>动作说明</summary>${info?.builtin?exerciseDiagram(info.diagram):''}<p>${esc(info?.instruction||'暂无说明')}</p></details></section>`;
  }).join('')}</div><button type="button" class="full ${d.exercises.length?'':'primary'}" data-action="pick-exercises">＋ 添加动作</button>`;
  if(d.exercises.length)body+=`<div class="rest-bar"><span id="rest-clock" class="timer"></span><button type="button" class="small" data-action="rest-start">休息</button><details><summary>调整时长</summary><label>秒<input type="number" id="rest-seconds" value="${state.settings.rest_seconds}" min="5" max="3600" aria-label="休息秒数"></label></details></div>`;
  body+=`<details class="record-options"><summary>更多选项</summary>${notes}<button type="button" class="small ghost" data-action="save-template">保存为模板</button><button type="button" class="small ghost danger" data-action="discard-draft">取消本次记录</button></details>`;
 }
 return {body:`<form id="workout-form">${body}<p class="inline-error" id="form-error" role="alert"></p></form>`,footer:`<button data-action="close" class="ghost">${strength&&!d.id?'稍后继续':'返回'}</button><button type="submit" form="workout-form" class="primary" ${strength&&!d.exercises.length?'disabled':''}>${live?'完成训练':'保存记录'}</button>`};
}
